package main

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// promptsIndexRel is the installer-owned aggregator file under a target's
// .claude/. It @-imports every installed prompt, so a user need only add a
// single `@prompts/_index.md` line to their CLAUDE.md to activate all of them.
// The installer fully owns this file and regenerates it on every install /
// uninstall, keeping the set of active prompts in step with what's installed —
// without ever editing the user's CLAUDE.md.
const promptsIndexRel = "prompts/_index.md"

// promptsIndexHeader documents the file's provenance for anyone who opens it.
// It deliberately contains no "@"-prefixed path: an @-directive here would be
// treated as a real import and could recurse into this very file.
const promptsIndexHeader = "<!-- Generated by the myagent installer. Do not edit; regenerated on every install/uninstall. Import this file from your CLAUDE.md to activate the prompts below. -->\n"

// installedPromptNames returns the leaf filenames of every prompt component the
// manifest currently records (e.g. "worktrees.md"), excluding the index itself,
// sorted for deterministic output.
func installedPromptNames(m *Manifest) []string {
	var names []string
	for rel := range m.Instances {
		if rel == promptsIndexRel {
			continue
		}
		dir, file := filepath.Split(filepath.ToSlash(rel))
		if strings.Trim(dir, "/") != "prompts" {
			continue
		}
		names = append(names, file)
	}
	sort.Strings(names)
	return names
}

// syncPromptsIndex rewrites prompts/_index.md so it @-imports exactly the prompt
// components currently recorded in the manifest, or removes the file when none
// remain. Imports are written relative to the index file's own directory, so a
// sibling prompt "prompts/x.md" becomes "@x.md". Returns the number of prompts
// linked (0 means the index was removed / left absent).
func syncPromptsIndex(targetClaude string, m *Manifest) (int, error) {
	names := installedPromptNames(m)
	dest := filepath.Join(targetClaude, filepath.FromSlash(promptsIndexRel))

	if len(names) == 0 {
		if err := os.Remove(dest); err != nil && !os.IsNotExist(err) {
			return 0, err
		}
		return 0, nil
	}

	var b strings.Builder
	b.WriteString(promptsIndexHeader)
	for _, n := range names {
		b.WriteString("@" + n + "\n")
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return 0, err
	}
	if err := os.WriteFile(dest, []byte(b.String()), 0o644); err != nil {
		return 0, err
	}
	return len(names), nil
}
